/**
 * /engine/data/disk/conf/ConfHand.java
 *
 * DESCRIPTION
 *
 * Copyright (C) 2026 Christian von Bohlen, J. K.
 */

package org.Game2D.engine.data.disk.conf;

import org.Game2D.engine.data.runtime.DataHand;
import org.Game2D.engine.data.runtime.Instance;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.util.Map;
import java.util.Properties;

public class ConfHand {

    /**
     * Set the path of the configuration file to be used
     *
     * @param confPath Path to the configuration file
     */
    public static void setConfPath(Path confPath) {

        if (confPath != null) DataHand.confPath = confPath;
        else DataHand.confPath = Path.of("./config.properties");

    }

    /**
     * Generate a new default config if no valid configuration file was specified
     */
    public static void generateConf() {

        File conf = new File(String.valueOf(DataHand.confPath));

        if (conf.exists()) return;

        ConfProvider.writeConf(getDefaultConf(), DataHand.confPath, "Autogenerated Game2D ConfigFile", true);

    }

    /**
     * Merge the specified config file with the config defaults
     * to always generate a valid config with all possible fields set
     */
    public static void updateConf() {

        Properties custom = ConfProvider.getConf(DataHand.confPath);
        Properties standard = getDefaultConf();

        for (Map.Entry<Object, Object> entry : standard.entrySet()) {
            if (!custom.containsKey(entry.getKey())) {
                custom.put(entry.getKey(), entry.getValue());
            }
        }

        ConfProvider.writeConf(custom, DataHand.confPath, "Autogenerated Game2D ConfigFile", true);
    }

    /**
     * Default config
     *
     * @return Default config
     */
    public static Properties getDefaultConf() {

        Properties properties = new Properties();

        try {
            properties.load(Instance.class.getResourceAsStream("/conf/default.properties"));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        return properties;

    }

}
