package de.Game2D.engine.core;

import de.Game2D.engine.core.managers.ActionMan;
import de.Game2D.engine.core.managers.RenderMan;

import de.Game2D.engine.core.handlers.Keyhand;
import de.Game2D.engine.utils.ConfProvider;

import javax.swing.*;
import java.io.File;
import java.nio.file.Path;
import java.util.Properties;

public class Instance {

    public  Path confPath = Path.of("./config.properties");

    //Manager
    public final ActionMan actMan;
    public final RenderMan rndMan;

    //Handlers
    public final Keyhand keyHandler;


    //Window
    JFrame window;

    //Gamelogicelements
    

    public Instance(Path confPath) {

        setConfPath(confPath);

        //Initialisatioin
        actMan = new ActionMan(this);

        rndMan = new RenderMan(this);

        keyHandler = new Keyhand();
    }

    private void setConfPath(Path confPath) {

        if (confPath != null) this.confPath = confPath;

        generateConf();

    }

    private void generateConf() {

        File conf = new File(String.valueOf(confPath));

        if (conf.exists()) return;

        Properties properties = new Properties();
        properties.setProperty("game2d.core.tps", "60");
        properties.setProperty("game2d.core.fps", "120");
        properties.setProperty("game2d.core.showDebugScreen", "false");

        ConfProvider.writeConf(properties, confPath, "Autogenerated Game2D ConfigFile", true);

    }

    public void start(String windowTitle){

        //Loading Window
        loadWindow(windowTitle);

        //Starting Managerloops

    }

    private void loadWindow(String windowTitle){

        window = new JFrame();

        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setExtendedState(window.MAXIMIZED_BOTH);
        window.setUndecorated(true);
        window.setResizable(false);
        window.setTitle(windowTitle);

        window.add(rndMan);

        window.pack();

        window.setLocationRelativeTo(null);
        window.setVisible(true);

    }

}
