package org.Game2D.engine.core.handlers;

import org.Game2D.engine.utils.ConfProvider;

import java.io.File;
import java.nio.file.Path;
import java.util.Properties;

public class ConfHand {

    public static void setConfPath(Path confPath) {

        if (confPath != null) DataHand.confPath = confPath;
        else DataHand.confPath = Path.of("./config.properties");

    }

    public static void generateConf() {

        File conf = new File(String.valueOf(DataHand.confPath));

        if (conf.exists()) return;

        ConfProvider.writeConf(getDefaultConf(), DataHand.confPath, "Autogenerated Game2D ConfigFile", true);

    }

    public static void updateConf() {

        Properties custom = ConfProvider.getConf(DataHand.confPath);
        Properties standart =getDefaultConf();

        for (int i = 0; i < standart.size(); i++) {
            //if (custom.containsKey(standart.get))
        }

    }

    public static Properties getDefaultConf() {

        Properties properties = new Properties();

        properties.setProperty("game2d.core.tps", "60");
        properties.setProperty("game2d.core.fps", "120");
        properties.setProperty("game2d.core.showDebugScreen", "false");
        properties.setProperty("game2d.reder.hitboxes", "false");

        return properties;

    }

}
