# GameLoop
game2d.game_loop.enable_hardware_acceleration = true
game2d.game_loop.target_tps = 60
game2d.game_loop.update_distance = 8

# Chunks
game2d.chunks.chunk_size = 1048

# Graphics
game2d.graphics.target_fps = 60
game2d.graphics.render_distance = 16
game2d.graphics.render_effects = false

# Debug
game2d.debug.tools.render_debug_screen = false
game2d.debug.graphics.render_hitboxes = false
game2d.debug.graphics.render_chunk_borders = false